### PR TITLE
Fix the logic

### LINKED ISSUE #56: Script failed when 'runner-results' folder not exist or if not empty
Hi,

in the start script, there is a line code that remove the 'runner-results' folder but the script throw an exception in 2 cases:
-> when this folder not exist
-> when this folder exist and it contains files

So before run the cmd, i must clean the folder or create a empty 'runner-results' folder. Could you handle this exception?

> cypress-parallel -s cy:run -t 4 -d cypress/integration/ -p cypress-report-config.json

(node:30920) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, rmdir 'C:\Personal_Unsaved\Projet\front-end\runner-results'
    at Object.rmdirSync (fs.js:684:3)
    at cleanResultsPath (C:\Personal_Unsaved\Projet\front-end\node_modules\cypress-parallel\cli.js:19:6)
    at start (C:\Personal_Unsaved\Projet\front-end\node_modules\cypress-parallel\cli.js:23:3)
    at Object.<anonymous> (C:\Personal_Unsaved\Projet\front-end\node_modules\cypress-parallel\cli.js:124:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
(node:30920) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30920) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### PR DESCRIPTION
**Pull request by hiroyone**
fix #56 

The cleanResultsPath method should have an empty folder, but the current logic was removing the directory.
The fixed logic cleans up all files in the directory but keep the directory itself.

### CODE REVIEW

**Comment by aaron-qa** [comment]
@hiroyone any idea when this will get reviewed/merged? I'm facing the issue this appears to fix.

**Comment by hiroyone** [comment]
Let's ask the creator.

@tnicola 
Hello.
How can we get an approval and merge this PR.

**Comment by tnicola** [comment]
Thanks for your contribution @hiroyone !It's now merged and published in 0.10.0

File: lib/cli.js [hunk 1]
```diff
@@ -15,9 +15,18 @@ const {
...
-  fs.remove(resultsPath);
-}
+function cleanResultsPath() { 
+  if(!fs.existsSync(resultsPath)) {
+    fs.mkdirSync(resultsPath, { recursive: true }) 
+  } else {
+    fs.readdir(resultsPath, (err, files) => {
+      if (err) console.log(err); 
+        for (const file of files) {
+          fs.unlink(path.join('path here', file), err => { if (err) console.log(err); });
```
Comment (danyalaytekin) [inline lib/cli.js:25]: Hi @hiroyone - should the string `"path here"` have been present here?  I'm seeing it surface when I run the tool.

image

Comment (hiroyone) [reply lib/cli.js:25]: Oh it should be a mistake.
Instead of 'path here', resultsPath seems correct, isn't it?

Comment (hiroyone) [reply lib/cli.js:25]: Merged. https://github.com/tnicola/cypress-parallel/pull/149

Comment (danyalaytekin) [reply lib/cli.js:25]: Thank you @hiroyone for updating it so quickly!  I've tested and the error is gone.
